export enum ACTIONS {
  SET_AREA_ID = 'SET_AREA_ID',
  SET_MESSAGE = 'SET_MESSAGE',
  
  LOAD_ELECTION_RESULTS = 'LOAD_ELECTION_RESULTS',
  RECEIVE_ELECTION_RESULTS = 'RECEIVE_ELECTION_RESULTS',
  REQUEST_ELECTION_RESULTS = 'REQUEST_ELECTION_RESULTS',

  LOAD_GEODATA = 'LOAD_GEODATA',
  RECEIVE_GEODATA = 'RECEIVE_GEODATA',
  REQUEST_GEODATA = 'REQUEST_GEODATA',

  LOAD_DATA_FOR_AREA = 'LOAD_DATA_FOR_AREA',
  RECEIVE_DATA_FOR_AREA = 'RECEIVE_DATA_FOR_AREA',

  RESET_SELECT = 'RESET_SELECT'
}