export enum ACTIONS {
  SET_AREA_ID = 'SET_AREA_ID',
  LOAD_ELECTION_RESULTS = 'LOAD_ELECTION_RESULTS',
  RECEIVE_ELECTION_RESULTS = 'RECEIVE_ELECTION_RESULTS',
  REQUEST_ELECTION_RESULTS = 'REQUEST_ELECTION_RESULTS'
};